name: EllyLouage
favicon: null
layout_spectrum: 0.6139865750446916
typography_spectrum: 0.5692001031711698
title: Tips en tricks voor bewust(er) opvoeden
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f2f1f2'
    - '#291c2b'
    - '#d29e76'
    - '#a3705a'
    - '#cbc3cb'
  brandStrength: 0.1373697267845273
  lightness: 0.13104032562114298
  saturation: 0.29873059154488146
  rhythmicContrast: 0.5710966784972697
purpose: []
